[phases.setup]
aptPkgs = ["tesseract-ocr", "tesseract-ocr-jpn", "poppler-utils"]

[phases.install]
cmds = ["pip install -r src/furigana-api/requirements.txt"]

[start]
cmd = "python -m gunicorn --chdir src/furigana-api --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app"

[variables]
PYTHON_VERSION = "3.11"